// Load and merge two JSON files describing network hosts
// The two files have different schema but both have a MAC address field that can be used to
// pair records for merge

// * Get two file names from the CLI
// * Open both files and load them into memory
// * compare and detect matching records in both lists
// * generate a new record for every unique record in both lists
// * generate a single new record for each matching record in both lists

use clap::{App, Arg};

fn main() {

    let _matches = App::new("merge-hosts")
        .version("0.1.0")
        .author("Mark Lamourine <markllama@gmail.com>")
        .about("Merge two JSON files describing network hosts")
        .arg(
            Arg::with_name("scan-file")
                .short("s")
                .value_name("SCAN_FILE")
                .help("A JSON file generated by an NMAP scan")
                .required(true)
                .min_values(1)
        )
        .arg(
            Arg::with_name("dhcp-file")
                .short("d")
                .value_name("DHCP_FILE")
                .help("A converted file from a DHCP service")
                .required(true)
                .min_values(1)
        )
        .get_matches();

    println!("{:#?}", _matches);
}

// fn process_command_line() {
//
// }
